### PR TITLE
make all-supplements arch specific

### PR DESCRIPTION
**Pull request by k0da**
A good reason to split them is different architectures have
different set of kernel drivers.

Signed-off-by: Dinar Valeev <dvaleev@suse.com>

### CODE REVIEW

**Comment by coolo** [comment]
LGTM, but I can't test

**Comment by DimStar77** [comment]
I don't think we should change the definition of released products - they are not going to be rebuilt anyway (13.2, leap 42.1); changing 'Factory' and 42.2 sounds fair though

**Comment by k0da** [comment]
@DimStar77 in case somebody will try to build it again... Just keep it sane

**Comment by coolo** [comment]
and remove them afterwards so that noone tries to rebuild them - they will fail most likely :)

**Comment by k0da** [comment]
@coolo @DimStar77 done

**Comment by k0da** [comment]
can it be merged?

**Comment by k0da** [comment]
ping

**Comment by nilxam** [comment]
looks ok to me. will merge it after snapshot 20160710 was out.

**Pull request merged**
