### PR TITLE
 Enable kubic for AArch64

### PR DESCRIPTION
**Pull request by ggardet**

### CODE REVIEW

**Comment by ggardet** [comment]
@dirkmueller Could you review, please?

**Comment by ggardet** [comment]
Thanks @dirkmueller

**Comment by DimStar77** [comment]
output/* and the ./t.* file should not be part of the PR

**Comment by ggardet** [comment]
@DimStar77 ok, so removing commit 3a8f9166d160d5a71f9f3068523c36ca8594c89f is fine or should I keep the diff for opensuse/Factory/all-supplements.aarch64 ?

**Comment by DimStar77** [comment]
>so removing commit 3a8f916 is fine or should I keep the diff for opensuse/Factory/all-supplements.aarch64 ?

Should be fine - this is also an autogenerated file (even though it is not in output)

**Comment by ggardet** [comment]
Ok, I removed commit 3a8f916, so it should be fine now.

**Pull request merged**
